language: r
pandoc_version: 1.17.2
cache: packages

script:
  - Rscript knit.R

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: source
  target_branch: master
