language: r
pandoc_version: 1.17.2
cache: packages

script:
  - Rscript -e "servr::jekyll(serve = FALSE, command = 'false')"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
